baseurl = "https://annienajera.github.io"
title = "My Blog"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "pink"
  description = "Mi nombre es Ana Fer Nájera, tengo 21 años y te nivito a leer mi blog"
  copyright = "&copy;2017 MakingDevs"
  sidebarAbout = [
  
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "anafernandanajera@gmail.com"

  

  [params.social]
  name = "Get in touch"
  facebook      = "https://www.facebook.com/anafeerlala"
  email         = "anafernandanajera@gmail.com"
  twitter       = "https://twitter.com/Fer96Ana"
  linkedin      = "full profile url in linkedin"
  github        = "full profile url in github"

